Added App Service Terraform configuration and Terraform format check in a new Terraform Validate job.

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -43,7 +43,7 @@ jobs:
           docker build -f Dockerfile . -t tbeit/webgoat:$GITHUB_RUN_ID
 
       - name: Docker Hub Login
-        run: | 
+        run: |
           docker login -u tbeit -p ${{ secrets.DOCKER_PASSWORD }}
           echo '## Docker Scout Scan Results' >> $GITHUB_STEP_SUMMARY
 
@@ -56,3 +56,18 @@ jobs:
 
       - name: Push Docker Image to Docker Hub
         run: docker push tbeit/webgoat:$GITHUB_RUN_ID
+
+  terraform-validate:
+    runs-on: ubuntu-latest
+    environment: default
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: hashicorp/setup-terraform@v3
+
+      # Will check Terraform Configuration Formatting
+      # (any output of terraform fmt will be redirected to std error, failing the job)
+      - name: Terraform Format Check
+        run: |
+          cd automation/iac/app_svc/terraform
+          terraform fmt >&2
